# +-------------------------------------------------------------------------+
# | en/main.yaml - The Galactic Compendium of English Translations          |
# +-------------------------------------------------------------------------+

demo:
  hello: Hey {name}
