# +-------------------------------------------------------------------------+
# | sensors.yaml - Defining and configuring sensors                         |
# +-------------------------------------------------------------------------+

# Custom sensors
custom:
  # Custom sensor with name "demo"
  demo:
    label: "Demo Sensor"
    unit: "°C"
